"""
HTML 测试报告生成器
根据执行结果生成美观的 HTML 报告
"""
import json
from datetime import datetime
from typing import Dict, Any, List


REPORT_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>测试报告 - {suite_name}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #1a1a2e; padding: 32px; }}
.container {{ max-width: 1000px; margin: 0 auto; }}
.header {{ background: linear-gradient(135deg, #667eea, #764ba2); color: white; padding: 32px; border-radius: 16px; margin-bottom: 24px; }}
.header h1 {{ font-size: 28px; margin-bottom: 8px; }}
.header p {{ opacity: 0.85; font-size: 14px; }}
.summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 24px; }}
.summary-card {{ background: white; border-radius: 12px; padding: 20px; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
.summary-card .value {{ font-size: 32px; font-weight: 700; }}
.summary-card .label {{ font-size: 12px; color: #666; margin-top: 4px; }}
.summary-card.total .value {{ color: #333; }}
.summary-card.pass .value {{ color: #10b981; }}
.summary-card.fail .value {{ color: #ef4444; }}
.summary-card.time .value {{ color: #6366f1; }}
.pass-rate {{ background: white; border-radius: 12px; padding: 20px; margin-bottom: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
.pass-rate h3 {{ margin-bottom: 12px; }}
.rate-bar {{ height: 24px; background: #fee2e2; border-radius: 12px; overflow: hidden; }}
.rate-bar .fill {{ height: 100%; border-radius: 12px; transition: width 0.3s; }}
.rate-bar .fill.high {{ background: linear-gradient(90deg, #10b981, #34d399); }}
.rate-bar .fill.mid {{ background: linear-gradient(90deg, #f59e0b, #fbbf24); }}
.rate-bar .fill.low {{ background: linear-gradient(90deg, #ef4444, #f87171); }}
.rate-text {{ text-align: center; margin-top: 8px; font-size: 20px; font-weight: 700; }}
.results {{ background: white; border-radius: 12px; padding: 24px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }}
.results h3 {{ margin-bottom: 16px; }}
.result-item {{ border: 1px solid #e5e7eb; border-radius: 8px; margin-bottom: 12px; overflow: hidden; }}
.result-item.passed {{ border-left: 4px solid #10b981; }}
.result-item.failed {{ border-left: 4px solid #ef4444; }}
.result-header {{ display: flex; justify-content: space-between; align-items: center; padding: 12px 16px; cursor: pointer; }}
.result-header:hover {{ background: #f9fafb; }}
.result-header .title {{ font-weight: 600; }}
.result-header .badge {{ font-size: 12px; padding: 2px 10px; border-radius: 12px; font-weight: 600; }}
.badge.pass {{ background: #d1fae5; color: #065f46; }}
.badge.fail {{ background: #fee2e2; color: #991b1b; }}
.result-detail {{ padding: 0 16px 16px; display: none; font-size: 13px; color: #555; }}
.result-detail.open {{ display: block; }}
.result-detail .field {{ margin-bottom: 6px; }}
.result-detail .field strong {{ color: #333; }}
.footer {{ text-align: center; margin-top: 32px; color: #999; font-size: 12px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📋 测试报告</h1>
    <p>{suite_name} · {base_url} · {timestamp}</p>
  </div>

  <div class="summary">
    <div class="summary-card total"><div class="value">{total}</div><div class="label">总用例数</div></div>
    <div class="summary-card pass"><div class="value">{passed}</div><div class="label">通过</div></div>
    <div class="summary-card fail"><div class="value">{failed}</div><div class="label">失败</div></div>
    <div class="summary-card time"><div class="value">{duration}</div><div class="label">总耗时</div></div>
  </div>

  <div class="pass-rate">
    <h3>📊 通过率</h3>
    <div class="rate-bar"><div class="fill {rate_class}" style="width:{pass_rate}%"></div></div>
    <div class="rate-text" style="color:{rate_color}">{pass_rate}%</div>
  </div>

  <div class="results">
    <h3>📝 用例详情</h3>
    {result_items}
  </div>

  <div class="footer">
    <p>Generated by AI TestCase Generator v4.0 · {timestamp}</p>
  </div>
</div>
<script>
document.querySelectorAll('.result-header').forEach(h => {{
  h.addEventListener('click', () => h.nextElementSibling.classList.toggle('open'));
}});
</script>
</body>
</html>"""


RESULT_ITEM = """<div class="result-item {cls}">
  <div class="result-header" onclick="this.nextElementSibling.classList.toggle('open')">
    <span class="title">{case_id} · {title}</span>
    <span class="badge {badge_cls}">{badge_text}</span>
  </div>
  <div class="result-detail">
    <div class="field"><strong>步骤:</strong> {steps_completed}/{steps_total}</div>
    <div class="field"><strong>耗时:</strong> {duration}</div>
    <div class="field"><strong>结果:</strong> {message}</div>
  </div>
</div>"""


def generate_report_html(suite_name: str, base_url: str, results: List[Dict[str, Any]], duration_ms: int) -> str:
    """生成 HTML 测试报告"""
    total = len(results)
    passed = sum(1 for r in results if r.get("passed"))
    failed = total - passed
    pass_rate = round(passed / total * 100, 1) if total > 0 else 0

    if pass_rate >= 80:
        rate_class, rate_color = "high", "#10b981"
    elif pass_rate >= 50:
        rate_class, rate_color = "mid", "#f59e0b"
    else:
        rate_class, rate_color = "low", "#ef4444"

    items = []
    for r in results:
        p = r.get("passed", False)
        items.append(RESULT_ITEM.format(
            cls="passed" if p else "failed",
            case_id=r.get("case_id", ""),
            title=r.get("title", ""),
            badge_cls="pass" if p else "fail",
            badge_text="✅ 通过" if p else "❌ 失败",
            steps_completed=r.get("steps_completed", 0),
            steps_total=r.get("steps_total", 0),
            duration=f"{r.get('duration_ms', 0)/1000:.1f}s",
            message=r.get("message", "")[:200],
        ))

    duration_s = f"{duration_ms / 1000:.1f}s" if duration_ms < 60000 else f"{duration_ms / 60000:.1f}min"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return REPORT_TEMPLATE.format(
        suite_name=suite_name,
        base_url=base_url,
        timestamp=timestamp,
        total=total,
        passed=passed,
        failed=failed,
        duration=duration_s,
        pass_rate=pass_rate,
        rate_class=rate_class,
        rate_color=rate_color,
        result_items="\n".join(items),
    )
